version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
